export const ADD_TOAST_NOTIFICATION = '@next/ui/ADD_TOAST_NOTIFICATION';
export const REMOVE_TOAST_NOTIFICATION = '@next/ui/REMOVE_TOAST_NOTIFICATION';

export const SHOW_CONFIRMATION_MODAL = '@next/ui/SHOW_CONFIRMATION_MODAL';
export const HIDE_CONFIRMATION_MODAL = '@next/ui/HIDE_CONFIRMATION_MODAL';

export const ACTION_CONFIRMED = '@next/ui/ACTION_CONFIRMED';
export const ACTION_REJECTED = '@next/ui/ACTION_REJECTED';
